In [3]:
print("learning linear algebra")

learning linear algebra


In [3]:
import numpy as np

In [10]:
# a tensor is a matrix with multi dimensions i.e more than 2 dimension
tensor=np.array([[[1,2,3],[4,5,6]],[[10,20,30],[15,25,35]]])
print(tensor)
print(tensor.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [15 25 35]]]
(2, 2, 3)


In [11]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
mat_transpose=np.transpose(mat)
print(mat_transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [14]:
a=np.array([1,2,3,4])
b=np.transpose(a)
print(b)

[1 2 3 4]


In [15]:
rand_mat=np.random.random((3,3))
print(rand_mat)

[[0.30726391 0.66847463 0.38895201]
 [0.76498138 0.91179413 0.34342965]
 [0.02052334 0.03630224 0.96831789]]


## matrix multiplication 

In [17]:
# dot(mat1,mat2 ) --> multiply two matrices mat1 and mat2
print(np.dot(mat,rand_mat))

[[ 1.8987967   2.60096962  3.98076498]
 [ 5.17710258  7.45068264  9.08286363]
 [ 8.45540847 12.30039566 14.18496229]]


In [18]:
# element wise multiplication
print(mat*rand_mat)

[[0.30726391 1.33694926 1.16685603]
 [3.05992552 4.55897067 2.06057792]
 [0.14366341 0.29041793 8.714861  ]]


## broadcasting --> doing mathematical operations on arrays

In [19]:
print(mat**2)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


## norms of a vector --> (summation of all |x(i)|^p)^1/p

In [25]:
x=np.array([-5,3,10])

In [27]:
lp2=np.linalg.norm(x)
print(lp1)

11.575836902790225


In [28]:
lp1=np.linalg.norm(x,ord=1)
print(lp1)

18.0


In [30]:
lpinf=np.linalg.norm(x,ord=np.inf)
print(lpinf)

10.0


In [33]:
matt=np.array([[2,-2,1],[-1,2,-1],[2,-4,1]])
lp2=np.linalg.norm(matt,ord=2)
print(lp2)

5.9287221489704836


In [35]:
mat1=np.array([[1,-3,10],[-2,10,-7],[0,1,0],[0,0,0]])
mat2=np.array([[5,0],[-2,11],[-3,12]])
print(np.dot(mat1,mat2))

[[-19  87]
 [ -9  26]
 [ -2  11]
 [  0   0]]
