In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3,4])
print(a)
print(a[1])
print(a.shape)

[1 2 3 4]
2
(4,)


In [7]:
b=np.array([[1],[2],[3],[4]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [14]:
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c[1][2])

[[1 2 3]
 [4 5 6]]
(2, 3)
6


In [18]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
c=np.full((3,2),5)
print(c)

[[5 5]
 [5 5]
 [5 5]]


In [21]:
#->identitiy matrix of size n np.eye(n)
=np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [42]:
randmatrix=np.random.random((3,4))
print(randmatrix)

[[0.99037693 0.96311249 0.29932524 0.49753186]
 [0.44305613 0.04988505 0.88008106 0.6522031 ]
 [0.86917092 0.6760256  0.86912461 0.5565131 ]]


In [43]:
print(randmatrix[ : ,1])

[0.96311249 0.04988505 0.6760256 ]


In [44]:
randmatrix[1:3,1:3]=2 #slicing
print(randmatrix)

[[0.99037693 0.96311249 0.29932524 0.49753186]
 [0.44305613 2.         2.         0.6522031 ]
 [0.86917092 2.         2.         0.5565131 ]]


In [45]:
print(randmatrix.dtype)

float64


In [49]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x+y)
print(np.subtract(x,y))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [53]:
print(x*y)
print("\n")
print(np.divide(x,y))
print("\n")
print(np.sqrt(x))


[[ 5 12]
 [21 32]]


[[0.2        0.33333333]
 [0.42857143 0.5       ]]


[[1.         1.41421356]
 [1.73205081 2.        ]]


# important
## matrix multiplication/dot product

In [54]:
print(np.dot(x,y))

[[19 22]
 [43 50]]


## multiplication of vecotrs

In [55]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(np.dot(a,b))

30


In [56]:
print(sum(a))

10


In [59]:
print(np.sum(x))

10


In [60]:
print(sum(x)) #colum wise sum

[4 6]


## stack functiom

In [62]:
print(a)
b=b**2
print(b)


[1 2 3 4]
[ 4 16 36 64]


In [63]:
np.stack((a,b),axis=1)

array([[ 1,  4],
       [ 2, 16],
       [ 3, 36],
       [ 4, 64]])

In [68]:
c=np.stack((a,b),axis=0)
print(c)

[[ 1  2  3  4]
 [ 4 16 36 64]]


## reshape

In [67]:
print(c)

[[ 1  2  3  4]
 [ 4 16 36 64]]


In [71]:
c=c.reshape(4,2)
print(c)

[[ 1  2]
 [ 3  4]
 [ 4 16]
 [36 64]]


In [72]:
c=c.reshape(8,-1)
print(c)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 4]
 [16]
 [36]
 [64]]


## numpy random module

In [74]:
a=np.arange(10)+5;
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [75]:
# shuffle
np.random.shuffle(a)
print(a)

[ 6  7 11  5 14 10  9 13  8 12]


In [76]:
a=np.random.rand(2,3)
print(a)

[[0.85181194 0.83881622 0.53655608]
 [0.77631589 0.85481754 0.77328999]]


In [77]:
# return valuse of standard distribution
a=np.random.randn(2,3)
print(a)

[[ 1.51878527  0.25014044  1.08077583]
 [ 0.56192435 -0.59357762 -0.75937004]]


In [82]:
a=np.random.randint(1,5,10)
print(a)

[2 1 3 2 2 1 4 4 3 1]


In [90]:
element=np.random.choice([1,10,2,3,4])
print(element)

10


## numpy function statistics

In [96]:
a=np.array([[1,2,3],[4,5,6]])
print(np.min(a))
print(np.min(a,axis=1))

1
[1 4]


In [98]:
print(np.mean(a))

3.5


In [99]:
print(np.median(a))

3.5


In [104]:
# median is the midddle most valye in  a sorted array
b=np.array([1,2,3,4])
print(np.median(b))

2.5


In [111]:
#weighted average
print(np.average(a,weights=a))

4.333333333333333


In [113]:
#standard deviation 
#sigma=underoot(1/n*summation from 1 to n of (xi-u)^2)
#variance=sigma**2
print(np.std(b))
print(np.var(c))


1.118033988749895
447.6875


In [23]:
print(r'Python\n is the \n best')

Python\n is the \n best


In [2]:
4*5**2

100